services:
  ############################
  # Manager app + Dapr sidecar
  ############################
  manager:
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./manager:/app/manager
      - shared-db:/app/db
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
    depends_on:
      - shared-db
      - rabbitmq
      - manager-dapr
      - newsaccessor
    networks:
      - network-dapr

  manager-dapr:
    image: "daprio/daprd:edge"
    ports:
      - "3500:3500"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: [
      "./daprd",
      "-app-id", "manager",
      "-app-port", "8000",
      "-app-protocol", "http",
      "-components-path", "/dapr/components",
      "-dapr-http-port", "3500",
      "-dapr-grpc-port", "50001",
      "-config", "/dapr/config.yaml"
    ]
    volumes:
      - ./dapr:/dapr
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - shared-db
      - rabbitmq
    networks:
      - network-dapr

  ############################
  # Engine app + Dapr sidecar
  ############################
  engine:
    build:
      context: .
      dockerfile: ./engine/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./engine:/app/engine
     # - shared-db:/app/db
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
    depends_on:
      - manager
    networks:
      - network-dapr

  engine-dapr:
    image: "daprio/daprd:edge"
    command: 
      - "./daprd"
      - "-app-port"
      - "8000"
      - "-app-id"
      - "engine"
      - "-app-protocol"
      - "http"
      - "-dapr-http-port"
      - "3502"
      - "-components-path"
      - "./dapr/components"
      - "-config"
      - "./dapr/config.yaml"
    volumes:
      - ./dapr:/dapr
      - ./dapr/components:/dapr/components
    depends_on:
      - manager
    networks:
      - network-dapr

  ############################
  # HFAccessor app + Dapr sidecar
  ############################
  hfaccessor:
    build:
      context: .
      dockerfile: ./hfaccessor/Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./hfaccessor:/app/hfaccessor
      - shared-db:/app/db
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
    depends_on:
      - engine
    networks:
      - network-dapr

  hfaccessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "8000",
        "-app-id", "hfaccessor",
        "-app-protocol", "http",
        "-dapr-http-port", "3503",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        ]
    volumes:
      - ./dapr:/dapr
      - ./dapr/components:/dapr/components
    depends_on:
      - hfaccessor
    networks:
      - network-dapr

  ############################
  # EmailAccessor app + Dapr sidecar
  ############################
  emailaccessor:
    build:
      context: .
      dockerfile: ./emailaccessor/Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./emailaccessor:/app/emailaccessor
      #- shared-db:/app/db
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
    depends_on:
      - manager
      - rabbitmq
    networks:
      - network-dapr

  emailaccessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "8000",
        "-app-id", "emailaccessor",
        "-app-protocol", "http",
        "-dapr-http-port", "3504",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        ]
    volumes:
      - ./dapr:/dapr
      - ./dapr/components:/dapr/components
    depends_on:
      - emailaccessor
    networks:
      - network-dapr

  ############################
  # NewsAccessor app + Dapr sidecar
  ############################
  newsaccessor:
    build:
      context: .
      dockerfile: ./newsaccessor/Dockerfile
    ports:
      - "8007:8000"
    volumes:
      - ./newsaccessor:/app/newsaccessor
      #- shared-db:/app/db
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
    depends_on:
      - rabbitmq
    #restart: always
    networks:
      - network-dapr

  newsaccessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "8000",
        "-app-id", "newsaccessor",
        "-app-protocol", "http",
        "-dapr-http-port", "3505",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        ]
    volumes:
      - ./dapr:/dapr
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
    depends_on:
      - newsaccessor
     # - rabbitmq
    networks:
      - network-dapr

  ############################
  # UserAccessor app + Dapr sidecar
  ############################
  useraccessor:
    build:
      context: .
      dockerfile: ./useraccessor/Dockerfile
    ports:
      - "8006:8000"
    volumes:
      - ./useraccessor:/app/useraccessor
      - shared-db:/app/db
      - ./dapr/components:/dapr/components
    environment:
      - PYTHONPATH=/app
    depends_on:
      - manager
    networks:
      - network-dapr

  useraccessor-dapr:
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "8000",
        "-app-id", "useraccessor",
        "-app-protocol", "http",
        "-dapr-http-port", "3506",
        "-components-path", "./dapr/components",
        "-config", "./dapr/config.yaml",
        ]
    volumes:
      - ./dapr:/dapr
      - ./dapr/components:/dapr/components
    depends_on:
      - useraccessor
    networks:
      - network-dapr

  ############################
  # RabbitMQ
  ############################
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network-dapr 

  ############################
  # SQLite Database
  ############################
  shared-db:
    image: python:3.9-slim
    environment:
      - DATABASE_URL=sqlite:///./users.db
    volumes:
      - ./data:/app/data
    networks:
      - network-dapr
  
networks:
  network-dapr:
    driver: bridge

volumes:
  shared-db:
    driver: local
