apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://rabbitmq:5672"  
    - name: queueName
      value: my-queue
  scopes:
    - pubsub
