apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://rabbitmq:5672"  
    - name: username
      value: "user"
    - name: password
      value: "pass"
